#!/data/data/com.termux/files/usr/bin/bash

### Helpers

project="/sdcard/Termux"
apps="$project/apps"
me="$0"

start_app() {
  am start --user 0 -a "$1" -e name "$2"
}

run_action() {
  if grep -qs "$3" "$apps" || [ "$2" = Update ] || [ "$2" = Package ]
  then
    echo "$1"
    am broadcast -a "$2" -e name "$3"
  else
    echo App not found
  fi
}


### Commands

app() (
  run_action "Starting $1..." Launch "$1"
)

info() {
  run_action "Starting info $1..." Info "$1"
}

update() {
  run_action "Loading Apps..." Update
}

package() {
  run_action "Starting package $1..." Package "$1"
}

usage() {
cat <<EOF

 Usage:
  launch
      [ -a --app <app_name> ]        [ -u --update ]
      [ -i --info <app_name> ]       [ -u --help ]
      [ -p --package <app_package> ]

  Launch apps on android

   -a --app      -- open app
   -i --info     -- open app settings
   -p --package  -- open app from package
   -u --update   -- load all apps
   -h --help     -- show help

EOF
  exit
}


### Execution

if ! (( $# )); then # If no arguments
  usage
fi

case "$1" in
  -a|--app) app "$2";;
  -i|--info) info "$2";;
  -u|--update) update;;
  -p|--package) package "$2";;
  -h|--help) usage;;
  *) usage; shift;;
esac

