#!/data/data/com.termux/files/usr/bin/bash


### Helpers

me="$0"
project="/sdcard/Termux"
apps="$(cat $project/apps)"

start_app() {
  am start --user 0 -a "$1" -e name "$2"
}

run_action() {
  if grep -qs "$3" "$apps" || [ "$2" = Update ]
  then
    echo "$1"
    am broadcast -a "$2" -e name "$3"
  else
    echo App not found
  fi
}


### Commands

app() (
  run_action "Starting $1..." Launch "$1"
)

info() {
  run_action "Starting info $1..." Info "$1"
}

update() {
  run_action "Loading Apps..." Update
}

usage() {
cat <<EOU
Usage:
  launch [ options... ] app_name
    Launch apps on android

  -a --app      -- open app
  -i --info     -- open app settings
  -u --update   -- load all apps
  -h --help     -- show help
EOU
  exit
}


### Execution

if ! (( $# )); then # If no arguments
  usage
fi

case "$1" in
  -a|--app) app "$2";;
  -i|--info) info "$2";;
  -u|--update) update;;
  -h|--help) usage;;
  *) usage; shift;;
esac

